spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/FREE
    username: SYSTEM
    password: admin
    driver-class-name: oracle.jdbc.driver.OracleDriver
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: mmk
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html
#  api-docs:
#    enabled: true
#    path: /v3/api-docs

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

server:
  port: 8088
