spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/FREE
    username: SYSTEM
    password: admin
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
  security:
    user:
      password: Test12345#
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3.2:latest

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

server:
  port: 8099
