spring:
  application:
    name: admin-service
  security:
    user:
      password: Test12345#

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

server:
  port: 8091
